In [24]:
import pandas as pd
import numpy as np
import networkx as nx
from func.UsefulFunctions import *

In [25]:
groupDF = pd.read_parquet("./Data/Network_groupWikidata.parquet")

groupDF.head()

,group,groupLabel,genre,groupType,inception,countryOfOrigin,recordLabel,genreLabel,groupTypeLabel,countryOfOriginLabel,recordLabelLabel,influencedby,influencedbyLabel,musicBrainzID,article,statementCount,__index_level_0__
0,Q7730499,The Dodge Brothers,Q606089,Q215380,NaN,Q145,NaN,skiffle,musical group,United Kingdom,NaN,NaN,NaN,73487971-6ca4-4c47-a1c0-93cbea313a94,https://en.wikipedia.org/wiki/The_Dodge_Brothers,10.0,62848
1,Q5710946,Atlántica,Q854451,Q113292621,1988.0,Q29,NaN,Celtic music,folk music group,Spain,NaN,NaN,NaN,972adc0e-fd52-4d49-a58f-ba0cf646799d,NaN,16.0,55791
2,Q12949191,L'As Pagat Lo Capèu?,NaN,Q215380,NaN,Q142,NaN,NaN,musical group,France,NaN,NaN,NaN,NaN,NaN,2.0,145805
3,Q51028968,Legion,Q483352,Q215380,NaN,Q29,NaN,thrash metal,musical group,Spain,NaN,NaN,NaN,8024f604-76e6-446d-b11e-c3c5213fad19,NaN,8.0,91458
4,Q2529057,The Pierces,Q206159,Q215380,2000.0,Q30,Q155152,psychedelic rock,musical group,United States,Polydor Records,NaN,NaN,9f4452f2-0451-455a-80c4-c873dda66eca,https://en.wikipedia.org/wiki/The_Pierces,60.0,35764

In [26]:
graphInfluences = addToNetwork4(groupDF, "influencedby", "group", "has influenced", "influence", "Musical Group", "influencedbyLabel", "groupLabel")

In [27]:
graphRecordLabel = addToNetwork4(groupDF, "recordLabel", "group", "has/had group", "Record Label", "Musical Group","recordLabelLabel", "groupLabel")

In [28]:
graphGenre = addToNetwork4(groupDF, "genre", "group", "has been participated in by", "Genre", "Musical Artist", "genreLabel", "groupLabel")

In [29]:
firstGraph = nx.compose(graphInfluences, graphGenre)
groupGraph = nx.compose(firstGraph, graphRecordLabel)

In [30]:
genreGraph = nx.read_graphml("./graphs/groupsGraph.graphml")
groupGraph = nx.compose(genreGraph, groupGraph)

In [31]:
groupGraph.nodes["Q44190"]

{'EntityType': 'Musical Group', 'Label': 'Radiohead'}

In [32]:
groupGraph.nodes["Q11366"]

{'EntityType': 'Genre', 'Label': 'alternative rock'}

In [33]:
nx.write_graphml(groupGraph, "./graphs/groupsGraph.graphml")

In [38]:
#Get only british artists
britishGroups = groupDF[(groupDF["countryOfOriginLabel"] == "Northern Ireland") | (groupDF["countryOfOriginLabel"] == "Scotland")| (groupDF["countryOfOriginLabel"] == "England") | (groupDF["countryOfOriginLabel"] == "Wales") | (groupDF["countryOfOriginLabel"] == "United Kingdom") | (groupDF["countryOfOriginLabel"] == "United Kingdom of Great Britain and Northern Ireland") | (groupDF["countryOfOriginLabel"] == "United Kingdom of Great Britain and Ireland")]

display(britishGroups)

,group,groupLabel,genre,groupType,inception,countryOfOrigin,recordLabel,genreLabel,groupTypeLabel,countryOfOriginLabel,recordLabelLabel,influencedby,influencedbyLabel,musicBrainzID,article,statementCount,__index_level_0__,Type
0,Q7730499,The Dodge Brothers,Q606089,Q215380,NaN,Q145,NaN,skiffle,musical group,United Kingdom,NaN,NaN,NaN,73487971-6ca4-4c47-a1c0-93cbea313a94,https://en.wikipedia.org/wiki/The_Dodge_Brothers,10.0,62848,has been participated in by
6,Q4779162,Apartment,Q598929,Q215380,NaN,Q145,Q5692619,post-punk,musical group,United Kingdom,Heartbeat Productions,NaN,NaN,222f063d-0ebe-45e9-9d23-ccc5e1e9eb88,NaN,11.0,48983,has been participated in by
13,Q11036,The Rolling Stones,Q193355,Q127334927,1962.0,Q145,Q21077,blues rock,band,United Kingdom,Warner Music Group,NaN,NaN,b071f9fa-14b0-4217-8e97-eb41da73f598,https://en.wikipedia.org/wiki/The_Rolling_Stones,276.0,113905,has been participated in by
29,Q24025201,Disciples,Q874038,Q2088357,2013.0,Q145,Q208909,deep house,musical ensemble,United Kingdom,Parlophone,NaN,NaN,4038e71c-2dfc-40da-bfd7-99d636066bf6,https://en.wikipedia.org/wiki/Disciples_(produ...,52.0,87290,has been participated in by
33,Q273171,"Emerson, Lake & Palmer",Q944465,Q215048,1970.0,Q21,Q62266131,jazz rock,supergroup,England,Volt Records,NaN,NaN,ad996aef-cc1c-42ac-af5c-619c370f4b8a,"https://en.wikipedia.org/wiki/Emerson,_Lake_%2...",115.0,10649,has been participated in by
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184580,Q7152384,Paul McKenna Band,Q235858,Q215380,NaN,Q145,Q5604605,traditional folk music,musical group,United Kingdom,Greentrax Recordings,NaN,NaN,188c5e4e-931c-4a48-a50f-30dca5f1d060,https://en.wikipedia.org/wiki/Paul_McKenna_Band,13.0,57819,has been participated in by
184581,Q7751656,The Mirage,Q383982,Q215380,1965.0,Q145,Q49462460,psychedelic pop,musical group,United Kingdom,CBS,NaN,NaN,a177e9de-422a-4bfd-ac9c-15d14c8ab6be,https://en.wikipedia.org/wiki/The_Mirage_(band),18.0,63901,has been participated in by
184588,Q273171,"Emerson, Lake & Palmer",Q217467,Q215048,1970.0,Q21,Q7299616,art rock,supergroup,England,Razor & Tie,NaN,NaN,ad996aef-cc1c-42ac-af5c-619c370f4b8a,"https://en.wikipedia.org/wiki/Emerson,_Lake_%2...",115.0,10062,has been participated in by
184589,Q51132163,Black Foxxes,Q11365,Q215380,2013.0,Q21,Q1973834,grunge,musical group,England,Play It Again Sam,NaN,NaN,a004f886-1ef0-4ecb-b332-3f5824430ae9,https://en.wikipedia.org/wiki/Black_Foxxes,35.0,91491,has been participated in by
184613,Q1051417,Starsailor,Q183504,Q215380,2000.0,Q145,Q183412,indie rock,musical group,United Kingdom,EMI,NaN,NaN,fbd86487-ccb5-4a57-a860-cc3d360b5115,https://en.wikipedia.org/wiki/Starsailor_(band),64.0,26974,has been participated in by

In [39]:
graphInfluencesUK = addToNetwork4(britishGroups, "influencedby", "group", "has influenced", "influence", "Musical Group",
                                "influencedbyLabel", "groupLabel")
graphRecordLabelUK = addToNetwork4(britishGroups, "recordLabel", "group", "has/had group", "Record Label", "Musical Group",
                                 "recordLabelLabel", "groupLabel")
graphGenreUK = addToNetwork4(britishGroups, "genre", "group", "has been participated in by", "Genre", "Musical Artist",
                           "genreLabel", "groupLabel")
firstGraphUK = nx.compose(graphInfluencesUK, graphGenreUK)
ukGroupGraph = nx.compose(firstGraphUK, graphRecordLabelUK)
ukGroupGraph = nx.compose(genreGraph, ukGroupGraph)

In [40]:
ukGroupGraph.nodes["Q44190"]

{'EntityType': 'Musical Group', 'Label': 'Radiohead'}

In [41]:
nx.write_graphml(ukGroupGraph, "./graphs/BritishGroupsGraph.graphml")