In [1]:
import pandas as pd
import numpy as np
import networkx as nx
from func.UsefulFunctions import *

In [2]:
groupDF = pd.read_parquet("./Data/Network_groupWikidata.parquet")

groupDF.head()

,group,groupLabel,genre,groupType,inception,countryOfOrigin,recordLabel,genreLabel,groupTypeLabel,countryOfOriginLabel,recordLabelLabel,influencedby,influencedbyLabel,musicBrainzID,article,statementCount,__index_level_0__
0,Q18233,ABBA,Q76092,Q1135557,1970.0,Q34,Q7697852,glam rock,quartet,Sweden,Telstar,Q213793,Phil Spector,d87e52c5-bb8d-4da8-b941-9f4928627dc8,https://en.wikipedia.org/wiki/ABBA,551.0,149487
1,Q117456093,NaN,NaN,Q215380,NaN,Q1006,NaN,NaN,musical group,Guinea,NaN,NaN,NaN,NaN,NaN,4.0,205681
2,Q261,Linkin Park,Q20378,Q215380,1996.0,Q30,Q67030918,alternative metal,musical group,United States,Warner Records Inc.,Q1412298,Helmet,f59c5520-5f46-4d2c-b2c4-822eabf53419,https://en.wikipedia.org/wiki/Linkin_Park,261.0,133426
3,Q484255,Alice in Chains,Q11365,Q5741069,1987.0,Q30,Q183412,grunge,rock band,United States,EMI,Q25507,Accept,4bd95eea-b9f6-4d70-a36c-cfea77431553,https://en.wikipedia.org/wiki/Alice_in_Chains,131.0,20882
4,Q6168378,Wrust,Q483251,Q215380,2000.0,Q963,NaN,death metal,musical group,Botswana,NaN,NaN,NaN,2ce76cf6-9d1d-4842-8d2a-50d3e0e88cc1,https://en.wikipedia.org/wiki/Wrust,15.0,69939

In [3]:
graphInfluences = addToNetwork4(groupDF, "influencedby", "group", "has influenced", "influence", "Musical Group", "influencedbyLabel", "groupLabel")

In [4]:
graphRecordLabel = addToNetwork4(groupDF, "recordLabel", "group", "has/had group", "Record Label", "Musical Group","recordLabelLabel", "groupLabel")

In [5]:
graphGenre = addToNetwork4(groupDF, "genre", "group", "has been participated in by", "Genre", "Musical Artist", "genreLabel", "groupLabel")

In [6]:
firstGraph = nx.compose(graphInfluences, graphGenre)
groupGraph = nx.compose(firstGraph, graphRecordLabel)

In [7]:
genreGraph = nx.read_graphml("./graphs/groupsGraph.graphml")
groupGraph = nx.compose(genreGraph, groupGraph)

In [8]:
groupGraph.nodes["Q44190"]

{'EntityType': 'Musical Group', 'Label': 'Radiohead'}

In [9]:
groupGraph.nodes["Q11366"]

{'EntityType': 'Genre', 'Label': 'alternative rock'}

In [10]:
nx.write_graphml(groupGraph, "./graphs/groupsGraph.graphml")

In [11]:
#Get only british artists
britishGroups = groupDF[(groupDF["countryOfOriginLabel"] == "Northern Ireland") | (groupDF["countryOfOriginLabel"] == "Scotland")| (groupDF["countryOfOriginLabel"] == "England") | (groupDF["countryOfOriginLabel"] == "Wales") | (groupDF["countryOfOriginLabel"] == "United Kingdom") | (groupDF["countryOfOriginLabel"] == "United Kingdom of Great Britain and Northern Ireland") | (groupDF["countryOfOriginLabel"] == "United Kingdom of Great Britain and Ireland")]

display(britishGroups)

,group,groupLabel,genre,groupType,inception,countryOfOrigin,recordLabel,genreLabel,groupTypeLabel,countryOfOriginLabel,recordLabelLabel,influencedby,influencedbyLabel,musicBrainzID,article,statementCount,__index_level_0__,Type
24,Q11036,The Rolling Stones,Q206159,Q215380,1962.0,Q145,Q594126,psychedelic rock,musical group,United Kingdom,Rolling Stones Records,Q356598,Elmore James,b071f9fa-14b0-4217-8e97-eb41da73f598,https://en.wikipedia.org/wiki/The_Rolling_Stones,276.0,136803,has been participated in by
37,Q7776695,The Yetties,NaN,Q215380,NaN,Q145,NaN,NaN,musical group,United Kingdom,NaN,NaN,NaN,3b2d1c32-1f76-4683-82e3-18bbaf886e16,https://en.wikipedia.org/wiki/The_Yetties,9.0,168330,has been participated in by
74,Q15816280,Brutality Will Prevail,Q183862,Q215380,2005.0,Q145,Q28374316,metalcore,musical group,United Kingdom,Purgatory Records,NaN,NaN,d82627f5-d70e-44a1-81a4-e6e2700020d7,https://en.wikipedia.org/wiki/Brutality_Will_P...,22.0,93334,has been participated in by
86,Q1807302,Young Knives,Q217467,Q5741069,1998.0,Q145,NaN,art rock,rock band,United Kingdom,NaN,NaN,NaN,b26b4b58-10b6-42e9-ba80-b1addd4b0adf,https://en.wikipedia.org/wiki/Young_Knives,40.0,47462,has been participated in by
112,Q15862,Queen,Q38848,Q215380,1970.0,Q145,Q183412,heavy metal music,musical group,United Kingdom,EMI,Q203736,Cream,0383dadf-2a4e-4d10-a46a-e9e041da8eb3,https://en.wikipedia.org/wiki/Queen_(band),189.0,139960,has been participated in by
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214494,Q19697,Motörhead,Q211723,Q5741069,1975.0,Q145,Q1093518,speed metal,rock band,United Kingdom,GWR Records,Q465862,Steppenwolf,57961a97-3796-4bf7-9f02-a985a8979ae9,https://en.wikipedia.org/wiki/Mot%C3%B6rhead,140.0,146070,has been participated in by
214505,Q23057703,Café Society,Q186472,Q215380,1973.0,Q145,Q6429478,folk rock,musical group,United Kingdom,Konk,NaN,NaN,d012e5e9-709f-40c2-8b01-b185711e4743,https://en.wikipedia.org/wiki/Caf%C3%A9_Societ...,13.0,101092,has been participated in by
214508,Q940536,The Damned,Q3071,Q215380,1976.0,Q145,Q2265719,punk rock,musical group,United Kingdom,I.R.S. Records,Q332032,Alice Cooper,77d21c13-846f-4f48-9546-873949eff6ae,https://en.wikipedia.org/wiki/The_Damned_(band),128.0,29649,has been participated in by
214511,Q3989687,The Treatment,Q83270,Q215380,2008.0,Q145,Q38903,hard rock,musical group,United Kingdom,Universal Music Group,NaN,NaN,c9d64bd4-73ae-41e2-a5f9-e592d37e0422,https://en.wikipedia.org/wiki/The_Treatment_(b...,25.0,62630,has been participated in by
214531,Q101505,Deep Purple,Q206159,Q5741069,1968.0,Q145,Q523563,psychedelic rock,rock band,United Kingdom,Edel Records,Q131422,The Animals,79491354-3d83-40e3-9d8e-7592d58d790a,https://en.wikipedia.org/wiki/Deep_Purple,164.0,3917,has been participated in by

In [12]:
graphInfluencesUK = addToNetwork4(britishGroups, "influencedby", "group", "has influenced", "influence", "Musical Group",
                                "influencedbyLabel", "groupLabel")
graphRecordLabelUK = addToNetwork4(britishGroups, "recordLabel", "group", "has/had group", "Record Label", "Musical Group",
                                 "recordLabelLabel", "groupLabel")
graphGenreUK = addToNetwork4(britishGroups, "genre", "group", "has been participated in by", "Genre", "Musical Artist",
                           "genreLabel", "groupLabel")
firstGraphUK = nx.compose(graphInfluencesUK, graphGenreUK)
ukGroupGraph = nx.compose(firstGraphUK, graphRecordLabelUK)
ukGroupGraph = nx.compose(genreGraph, ukGroupGraph)

In [13]:
ukGroupGraph.nodes["Q44190"]

{'EntityType': 'Musical Group', 'Label': 'Radiohead'}

In [14]:
nx.write_graphml(ukGroupGraph, "./graphs/BritishGroupsGraph.graphml")

In [15]:
afgroupGraph = nx.ego_graph(groupGraph, "Q464369", radius=3, center=True, undirected = True).copy()
#electronicEgoGraph = nx.ego_graph(artistGraph, "Q9778", radius=2, center=True,undirected = True).copy()
#subgraph = nx.compose(electronicEgoGraph, bjorkEgoGraph)
print(len(afgroupGraph.nodes()))
nx.write_graphml(afgroupGraph, "./graphs/americanFootballEgoGraph.graphml")

11387