In [3]:
import polars as pl
import pandas as pd
import numpy as np
import altair as alt
import pyarrow
from numpy.ma.extras import unique
from polars import Null
import matplotlib.pyplot as plt
import squarify
import seaborn as sns

from func.UsefulFunctions import *

Find the missing people, so people who are on musicbrainz but not on wikidata

In [5]:
wikidataArtistDF = pd.read_parquet("./Data/Network_artistsWikidata.parquet")
mbArtistsData = pd.read_parquet("./Data/Network_personMBData.parquet")

display(wikidataArtistDF.head())
display(mbArtistsData.head())

,artist,occupation,gender,occupationLabel,genderLabel,countryCitizenship,influencedBY,influencedBYLabel,statementCount,genre,article,musicBrainzID,recordLabel,recordLabelLabel,countryCitizenshipLabel,genreLabel,artistLabel
0,Q3176190,Q639669,Q6581072,musician,female,Q30,NaN,NaN,NaN,Q43343,https://en.wikipedia.org/wiki/Linda_Gail_Lewis,a2fe484f-4f35-4e0e-a954-2f6d5843b009,Q7544232,Smash Records,United States,folk music,Linda Gail Lewis
1,Q8065552,Q183945,Q6581097,record producer,male,Q145,NaN,NaN,NaN,NaN,https://en.wikipedia.org/wiki/Zalon,19c43212-18cf-4f02-baff-b794de3cdf02,NaN,NaN,United Kingdom,NaN,Zalon
2,Q191819,Q806349,Q6581097,bandleader,male,Q174193,NaN,NaN,NaN,Q9730,https://en.wikipedia.org/wiki/George_Martin,26fa8b67-6c7f-406c-ad64-a1d070092df2,Q21077,Warner Music Group,United Kingdom of Great Britain and Ireland,classical music,George Martin
3,Q21934026,Q183945,Q6581097,record producer,male,NaN,NaN,NaN,NaN,Q37073,https://en.wikipedia.org/wiki/Andrew_Scheps,ee11737c-d50c-4b04-ae5f-56e1f6373116,NaN,NaN,NaN,pop music,Andrew Scheps
4,Q1005957,Q55960555,Q6581097,recording artist,male,Q28,NaN,NaN,NaN,NaN,NaN,6054baf8-3a47-4c3a-8c51-eb976f69ecfc,NaN,NaN,Hungary,NaN,László Földes

,id,name,type,gender,country,genres,isnis,ipis,life-span,genreList
0,fc926d23-4f61-4df5-8aaf-9f24109f660f,Zheng Yue Wen,Person,NaN,NaN,[],[],[],"{'end': None, 'begin': None, 'ended': False}",[]
1,595058cd-36fe-4994-8933-df92ff68ebd7,DJ Seinfeld,Person,Male,ES,[{'id': '8ae6fbbe-2dd0-432e-a176-6678f48dffb4'...,[0000000465763535],[],"{'end': None, 'begin': None, 'ended': False}","[bassline, breakbeat, breaks, club, dance, dee..."
2,4c6b0be1-3e90-430b-b208-e87945144be0,Trishita Recs,Person,Female,IN,[],[],[],"{'end': None, 'begin': None, 'ended': False}",[]
3,fe37b5c5-3c9f-48f4-9f9a-28939d0e3d77,Salvatore Marino,Person,Male,NaN,[],[],[],"{'end': None, 'begin': None, 'ended': False}",[]
4,c666baa0-ebbf-4103-8249-a53db676cece,Zoë Marie Federoff,Person,Female,US,[],[],[],"{'end': None, 'begin': '1992-05-25', 'ended': ...",[]

In [6]:
#Dataset of artists who are on MusicBrainz but not on Wikidata

#How many entities have a music brainz id
numberOfFolkWithMusicBrainzID = len(wikidataArtistDF[~wikidataArtistDF["musicBrainzID"].isnull()]["artist"].drop_duplicates())

print(f"There are {numberOfFolkWithMusicBrainzID} individuals with a music brainz id")

There are 179192 individuals with a music brainz id

In [8]:
#Using ID to check the individuals
peopleNotOnWikidataByID = mbArtistsData[~mbArtistsData["id"].isin(wikidataArtistDF["musicBrainzID"].unique())]

print(f"There are {len(peopleNotOnWikidataByID["id"].unique())} people not on wikidata based on MusicBrainzID")

There are 1392611 people not on wikidata based on MusicBrainzID

In [9]:
#Using just names
peopleNotONWikidataByName = mbArtistsData[~mbArtistsData["name"].isin(wikidataArtistDF["artistLabel"].unique())]
print(f"There are {len(peopleNotONWikidataByName["id"].unique())} people not on wikidata based on name")

There are 1332520 people not on wikidata based on name

In [ ]:
#What are the missing genres