In [5]:
import polars as pl
import pandas as pd
import numpy as mp
import altair as alt
import pyarrow
from func.UsefulFunctions import *

This notebook is for labelling the data from wikidata

In [6]:
artistDF = pd.read_csv("/home/aja25/Downloads/ArtistsData_FromWikidata/Query 107 - Unlabelled People with musical occupations (+subclass of musical occupation) + gender + occupation.csv")
occupationsDF = pd.read_excel("/home/aja25/Downloads/ArtistsData_FromWikidata/Annotated musical occupations (and the occupations from the subclases).xlsx")

display(artistDF.head(5))
display(occupationsDF.head(5))

,artist,occupation,gender
0,http://www.wikidata.org/entity/Q1511620,http://www.wikidata.org/entity/Q17303149,http://www.wikidata.org/entity/Q6581097
1,http://www.wikidata.org/entity/Q1558606,http://www.wikidata.org/entity/Q17303149,http://www.wikidata.org/entity/Q6581097
2,http://www.wikidata.org/entity/Q1559083,http://www.wikidata.org/entity/Q17303149,http://www.wikidata.org/entity/Q6581097
3,http://www.wikidata.org/entity/Q1575045,http://www.wikidata.org/entity/Q17303149,http://www.wikidata.org/entity/Q6581097
4,http://www.wikidata.org/entity/Q1577085,http://www.wikidata.org/entity/Q17303149,http://www.wikidata.org/entity/Q6581097

,occupation,occupationLabel,isItAllowed,Notes
0,http://www.wikidata.org/entity/Q1824074,Q1824074,No,NaN
1,http://www.wikidata.org/entity/Q158852,conductor,Yes,NaN
2,http://www.wikidata.org/entity/Q386854,drummer,Yes,NaN
3,http://www.wikidata.org/entity/Q130857,disc jockey,Yes,NaN
4,http://www.wikidata.org/entity/Q488205,singer-songwriter,Yes,NaN

In [7]:
occupationsDF.occupation = occupationsDF.occupation.map(getEntityIDValue)
artistDF = artistDF.map(getEntityIDValue)

display(artistDF.head(5))
display(occupationsDF.head(5))

     artist occupation    gender
0  Q1511620  Q17303149  Q6581097
1  Q1558606  Q17303149  Q6581097
2  Q1559083  Q17303149  Q6581097
3  Q1575045  Q17303149  Q6581097
4  Q1577085  Q17303149  Q6581097

  occupation    occupationLabel isItAllowed Notes
0   Q1824074           Q1824074          No   NaN
1    Q158852          conductor         Yes   NaN
2    Q386854            drummer         Yes   NaN
3    Q130857        disc jockey         Yes   NaN
4    Q488205  singer-songwriter         Yes   NaN

In [10]:
allowedOccupations = occupationsDF[occupationsDF["isItAllowed"] == "Yes"][["occupation","occupationLabel"]]
display(allowedOccupations.head(5))

  occupation    occupationLabel
1    Q158852          conductor
2    Q386854            drummer
3    Q130857        disc jockey
4    Q488205  singer-songwriter
5    Q118865        clarinetist